name: Online temperature metrics agent

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: agent/online-temp-metrics
    steps:
      - uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action, setup docker
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Release checks
        run: |
          pip3 install -r ci/requirements.txt
          inv ci-build
