name: Online temperature metrics agent

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: agent/online-temp-metrics
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/docker-run-action
      - name: Release build
        uses: addnab/docker-run-action@v3
        with:
          image: juanrh/online-temp-metrics-ci:latest
          shell: bash
          options: | 
            -e ONLINE_TEMP_METRICS_SRC_DIR="${{ github.workspace }}" \
            -v "${{ github.workspace }}:/home/conan/project" \
            -v "/var/run/docker.sock:/var/run/docker.sock"
          run: inv release --extra-linter-options --filter=-build/header_guard
