name: Online temperature metrics agent

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      # https://github.community/t/docker-action-cant-create-folder-in-runners-home-directory/17816/3
      # https://stackoverflow.com/questions/57830375/github-actions-workflow-error-permission-denied
      - name: Prepare output directories
        run: sudo mkdir -p "${{ github.workspace }}/agent/online-temp-metrics/build" && sudo mkdir -p "${{ github.workspace }}/agent/online-temp-metrics/cross_build"
      # https://github.com/marketplace/actions/docker-run-action
      - name: Release build
        uses: addnab/docker-run-action@v3
        with:
          image: juanrh/online-temp-metrics-ci:latest
          shell: bash
          # NOTE: new line (even with ' \') in options leads to "docker: invalid reference format"
          options: -e ONLINE_TEMP_METRICS_SRC_DIR="${{ github.workspace }}/agent/online-temp-metrics" -v ${{ github.workspace }}/agent/online-temp-metrics:/home/conan/project -v /var/run/docker.sock:/var/run/docker.sock
          run: pwd && ls -al && inv release --extra-linter-options --filter=-build/header_guard
